routes/backend.php
<?php

use App\Http\Controllers\Backend\AdminController;
use App\Http\Controllers\Backend\ContentPageController;
use App\Http\Controllers\Backend\HomeController;
use Illuminate\Support\Facades\Route;

Route::prefix('')->as('backend.')->group(function () {
    Route::get('login', [AdminController::class,'login'])->name('login');
    Route::post('dologin', [AdminController::class,'dologin'])->name('dologin');
    
    Route::middleware('auth:backend')->group(function () {
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index')->name('logs');
        Route::get('', [HomeController::class, 'index'])->name('home');
        Route::get('logout', [AdminController::class,'logout'])->name('logout');
        Route::any('change_password', [AdminController::class,'ChangePassword'])->name('change_password');
        //Static content
        Route::resource('content_page', ContentPageController::class,['only' => ['index', 'show', 'edit', 'update']]);
    });



});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

app/Models/Backend/Admin.php
<?php

namespace App\Models\Backend;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Admin extends Authenticatable
{
    use Notifiable;

    protected $guard = 'backend';
    protected $primaryKey = 'iAdminId';
    public $timestamps = false;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'vAdminUuid','vFirstName','vLastName','vEmail','txDescription','iRoleId','iLastLoginAt','iCreatedAt','iUpdatedAt'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'iAdminId','vPassword','tiStatus','tiIsDeleted','remember_token'
    ];

    protected $casts = [
        'iCreatedAt' => 'integer',
        'iUpdatedAt' => 'integer',
        'tiStatus' => 'integer',
        'tiIsDeleted' => 'integer'
    ];

    public function getAuthPassword() {
        return $this->vPassword;
    }
    
    public function adminRole(){   
        return $this->belongsTo('App\Http\Backend\Models\Role', 'iRoleId', 'iRoleId');
    }
}

app/Models/Backend/ContentPage.php
<?php

namespace App\Models\Backend;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ContentPage extends Model
{
    use HasFactory;

    protected $primaryKey = 'iPageId';
    public $timestamps = false;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'vPageUuid','vPageName','vSlug','txContent','tiIsActive','iCreatedAt','iUpdatedAt'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'iPageId'
    ];
}

app/Models/SwaggerModels/v1/ContentPages.php
<?php
/**
 * @OA\Get(
 *      path="/content-pages/{vSlug}",
 *      tags={COMMON_TAG},
 *      summary="Static content pages",
 *      operationId="contentPages",
 *      @OA\Parameter(
 *          name="vSlug",
 *          in="path",
 *          required=true,
 *          @OA\Schema(type="string"),
 *          description="about_us"
 *      ),
 *      @OA\Response(
 *         response=200,
 *         description="success",
 *         @OA\JsonContent(ref="#/components/schemas/ContentPageResponse"),
 *      ),
 *      @OA\Response(
 *         response=400,
 *         description="Error",
 *         @OA\JsonContent(ref="#/components/schemas/CommonFields"),
 *      )
 * )
 */

/**
 * @OA\Schema(
 *   schema="ContentPageResponse",
 *   type="object",
 *   allOf={
 *     @OA\Schema(ref="#/components/schemas/CommonFields"),
 *     @OA\Schema(
 *          @OA\Property(
 *              property="responseData", 
 *              type="object",
 *              ref="#/components/schemas/ContentPageResponseFields"
 *          )
 *      )
 *   }
 * )
 */


 /**
 * @OA\Schema(
 *   schema="ContentPageResponseFields",
 *   type="object",
 *   @OA\Property(
 *       property="vPageName", 
 *       type="string"
 *   ),
 *   @OA\Property(
 *       property="txContent", 
 *       type="string"
 *   ),
 *   @OA\Property(
 *       property="iUpdatedAt", 
 *       type="integer",
 *       format="int32"
 *   )
 * )
 */

app/Http/Controllers/Backend/AdminController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Common;
use App\Models\Backend\Admin;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Lang;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\MessageBag;

class AdminController extends Controller {

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct() {
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function login(Request $request) {
        if (!Auth::guard('backend')->check()) {
            $model = new Admin();
            return view('backend.admin.login',compact('model'));
        }

        return redirect()->guest(route('backend.home'));
    }

    public function dologin(Request $request) {
        // Validate form data
        $this->validate($request, [
            'vEmail' => 'required|email',
            'vPassword' => 'required',
            'iTimezoneOffset' => 'required|integer'
        ]);

        $remember_me = $request->has('remember_me') ? true : false; 
        $isLogin = Auth::guard('backend')->attempt([
            'vEmail' => $request->vEmail, 
            'password' => $request->vPassword,
            'tiIsDeleted' => 0
        ],$remember_me);
        if ($isLogin) {
            $admin = Auth::guard('backend')->user();
            if($admin->tiIsActive == 1) {
                DB::update('update admins set iLastLoginAt = ? where iAdminId = ?', [time(),$admin->iAdminId]);
                return redirect()->guest(route('backend.home'));
            } else {
                Auth::logout();
                $request->session()->flush();
                $request->session()->flash('error', 'Your account is inactive');
                return redirect()->back()->withInput($request->only('vEmail'));
            }
        }
        // Authentication failed, redirect back to the login form
        $request->session()->flash('error', 'Wrong email or password.');
        return redirect()->back()->withInput($request->only('vEmail'));
    }

    public function logout(Request $request) {
        Auth::logout();

        $request->session()->flush();
        $request->session()->regenerate();
        return redirect()->guest(route('backend.login'));
    }

    public function error() {
        return view('backend.admin.error');
    }

    //Change password
    public function ChangePassword(Request $request,MessageBag $message_bag) {
        $user = Auth::user();
        if($request->isMethod("post")) {
            // Validate form data
            $this->validate($request, [
                'vCurrentPassword' => 'required',
                'vNewPassword' => 'required|min:8|different:vCurrentPassword',
                'vConfirmPassword' => 'required_with:vNewPassword|same:vNewPassword',
            ]);

            if (!Hash::check($request->vCurrentPassword, $user->vPassword)) { 
                $message_bag->add('vCurrentPassword', __("message.old_password_wrong"));
                return Redirect::back()->withInput($request->all())->withErrors($message_bag);
            }

            $user->vPassword = Hash::make($request->vNewPassword);
            $user->save();

            FormSuccessResponse($request,"message.password_changed");
            return redirect()->route('backend.change_password');
        }
        return view('backend.admin.changepassword');
    }

    //Profile
    public function Profile(Request $request,MessageBag $message_bag) {
        $model = Auth::user();
        $validation_rules = $model->Validate("profile");
        if($request->isMethod("post")) {
            $this->ValidateForm($request,$validation_rules);
            $time = time();
            $model->vFirstName = $request->vFirstName;
            $model->vLastName = $request->vLastName;
            $model->iUpdatedAt = $time;
            $model->save();

            FormSuccessResponse($request,"message.profile_updated");
            return redirect()->route('backend.profile');
        }

        return view('backend.admin.profile',compact('model','validation_rules'));
    }
}

app/Http/Controllers/Backend/ContentPageController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Backend\ContentPage;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class ContentPageController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = ContentPage::select("vPageUuid","vPageName","vSlug","iUpdatedAt")->get();
        return view('backend.content_page.index',compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($uuid)
    {
        $model = $this->getPage($uuid);
        return view('backend.content_page.show',compact('model'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($uuid)
    {
        $model = $this->getPage($uuid);
        return view('backend.content_page.edit',compact('model'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $uuid)
    {
        $this->validate($request, [
            'vPageName' => 'required|string',
            'txContent' => 'required',
                ], [
            'vPageName.required' => 'The page name field is required.',
            'txContent.required' => 'The content field is required.',
        ]);
        try {
            $model = $this->getPage($uuid);
            $model->vPageName = $request->vPageName;
            $model->txContent = $request->txContent;
            $model->iUpdatedAt = time();
            if ($model->update()) {
                $request->session()->flash('success', $request->vPageName.' content updated successfully.');
            } else {
                $request->session()->flash('error', 'Fail to update '.$request->vTitle.' content.');
            }
            return redirect()->route('backend.content_page.show', ['content_page' => $uuid]);
        } catch (\Exception $ex) {
            $request->session()->flash('error', __('message.something_wrong'));
            return redirect()->route('backend.content_page.edit', ['content_page' => $uuid]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    //Get page detail
    private function getPage($uuid) {
        $model = ContentPage::where(['vPageUuid' => $uuid])->first();
        if(empty($model)) {
            throw new NotFoundHttpException();
        }
        return $model;
    }
}

app/Http/Controllers/Backend/Controller.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController {
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;

    public function ValidateForm($request,$validtion_rules) {
        $rules = (isset($validtion_rules["rules"]) && !empty($validtion_rules["rules"])) ? $validtion_rules["rules"] : [];
        $message = (isset($validtion_rules["messages"]) && !empty($validtion_rules["messages"])) ? $validtion_rules["messages"] : [];
        $this->validate($request, $rules, $message);
    }
}

app/Http/Controllers/Backend/HomeController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;

class HomeController extends Controller
{
    public function index(Request $request){
        return view('backend.home.index');
    }
}

resources/views/backend/content_page/edit.blade.php
@extends('backend.layouts.main')
@section('title', CONTENT_PAGE_LABEL)
@php ($title = 'Edit: '.$model->vPageName)

@section('breadcrumb')
<li class="breadcrumb-item"><a href="{{ route('backend.content_page.index') }}">{{ CONTENT_PAGE_LABEL }} list</a></li>
<li class="breadcrumb-item active" aria-current="page">{{ $title }}</li>
@stop


<!-- Page content --->
@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">{{ $title }}</h3>
            </div>
            <div class="card-body">
            <form method="POST" action="{{ route('backend.content_page.update',['content_page' => $model->vPageUuid]) }}" autocomplete="off">
                @method('PUT')
                {{ csrf_field() }}
                <div class="form-group">
                    <label>Slug</label>
                    <input type="text" name="vSlug" class="form-control" placeholder="Slug" value="{{ (!empty(old())) ? old('vSlug') : $model->vSlug }}" <?= ($model->exists) ? 'readonly' : '' ?>>
                    <span class="text-danger">{{ $errors->first('vSlug') }}</span>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label>Page name</label>
                            <input type="text" name="vPageName" class="form-control" placeholder="Title" value="{{ (!empty(old())) ? old('vPageName') : $model->vPageName }}">
                            <span class="text-danger">{{ $errors->first('vPageName') }}</span>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label>Content</label>
                            <textarea name="txContent" class="form-control" id="txContent" placeholder="Write some text here.." rows="5">{{ (!empty(old())) ? old('txContent') : $model->txContent }}</textarea>
                            <span class="text-danger">{{ $errors->first('txContent') }}</span>
                        </div>
                    </div>
                </div>

                <button type="submit" class="btn btn-primary">Submit</button>

            </form>
            </div>
        </div>
    </div>
</div>
@stop

<!--- Append javascript --->
@push('script')
<script src="{{ asset('theme/plugins/ckeditor/ckeditor.js') }}"></script>
<script>
$(function () {
    CKEDITOR.replace('txContent',{
        enterMode: CKEDITOR.ENTER_BR
    });
})
</script>
@endpush

resources/views/backend/content_page/index.blade.php
@extends('backend.layouts.main')
@section('title', CONTENT_PAGE_LABEL)


@section('breadcrumb')
<li class="breadcrumb-item active" aria-current="page">{{ CONTENT_PAGE_LABEL }} list</li>
@stop


<!-- Page content --->
@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">{{ CONTENT_PAGE_LABEL }}</h3>
            </div>

            <div class="card-body">
                <div class="dt-responsive">
                    <table class="table table-bordered table-sm">
                        <thead>
                            <tr>
                                <th style="width: 50px;">#</th>
                                <th>Title</th>
                                <th>Slug</th>
                                <th style="width: 170px;">Updated at</th>
                                <th style="width: 130px;"></th>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach($data as $key => $val)
                            <tr>
                                <td>{{ $key+1 }}</td>
                                <td>{{ $val->vPageName }}</td>
                                <td>{{ $val->vSlug }}</td>
                                <td>{{ date('Y-d-m h:i A',$val->iUpdatedAt) }}</td>
                                <td>
                                    <a href="{{ route('backend.content_page.show',['content_page' => $val->vPageUuid]) }}" class="btn btn-primary btn-xs"><i class="fas fa-eye"></i></a>
                                    <a href="{{ route('backend.content_page.edit',['content_page' => $val->vPageUuid]) }}" class="btn btn-info btn-xs"><i class="fas fa-edit" data-toggle="tooltip" data-placement="top"></i></a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@stop

resources/views/backend/content_page/show.blade.php
@extends('backend.layouts.main')
@section('title', CONTENT_PAGE_LABEL)
@php ($title = $model->vPageName)

@section('breadcrumb')
<li class="breadcrumb-item"><a href="{{ route('backend.content_page.index') }}">{{ CONTENT_PAGE_LABEL }} list</a></li>
<li class="breadcrumb-item active" aria-current="page">{{ $title }}</li>
@stop


<!-- Page content --->
@section('content')
<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">{{ $title }}</h3>
                <div class="text-right">
                    <a href="{{ route('backend.content_page.edit',['content_page' => $model->vPageUuid]) }}" class="btn btn-info btn-sm"><i class="fa fa-edit"></i> Edit</a>
                </div>
            </div>
            <div class="card-body">
                <div class="dt-responsive">
                    <table id="datatable" class="table table-bordered table-sm">
                        <tr>
                            <th style="width: 300px;">Slug</th>
                            <td>{{ $model->vSlug }}</td>
                        </tr>
                        <tr>
                            <th>Title</th>
                            <td>{{ $model->vPageName }}</td>
                        </tr>
                        <tr>
                            <th>Description</th>
                            <td>{!! $model->txContent !!}</td>
                        </tr>
                        <tr>
                            <th style="width: 300px;">Updated at</th>
                            <td>{{ date('Y-m-d h:i A', $model->iUpdatedAt) }}</td>
                        </tr>
                        <tr>
                            <th style="width: 300px;">Created at</th>
                            <td>{{ date('Y-m-d h:i A', $model->iCreatedAt) }}</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@stop