routes/backend.php
<?php

use App\Http\Controllers\Backend\AdminController;
use App\Http\Controllers\Backend\ContentPageController;
use App\Http\Controllers\Backend\HomeController;
use Illuminate\Support\Facades\Route;

Route::prefix('')->as('backend.')->group(function () {
    Route::get('login', [AdminController::class,'login'])->name('login');
    Route::post('dologin', [AdminController::class,'dologin'])->name('dologin');
    
    Route::middleware('auth:backend')->group(function () {
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index')->name('logs');
        Route::get('', [HomeController::class, 'index'])->name('home');
        Route::get('logout', [AdminController::class,'logout'])->name('logout');
        Route::any('change_password', [AdminController::class,'ChangePassword'])->name('change_password');
        //Static content
        Route::resource('content_page', ContentPageController::class,['only' => ['index', 'show', 'edit', 'update']]);
    });



});

routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

app/Models/Backend/Admin.php
<?php

namespace App\Models\Backend;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Admin extends Authenticatable
{
    use Notifiable;

    protected $guard = 'backend';
    protected $primaryKey = 'iAdminId';
    public $timestamps = false;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'vAdminUuid','vFirstName','vLastName','vEmail','txDescription','iRoleId','iLastLoginAt','iCreatedAt','iUpdatedAt'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'iAdminId','vPassword','tiStatus','tiIsDeleted','remember_token'
    ];

    protected $casts = [
        'iCreatedAt' => 'integer',
        'iUpdatedAt' => 'integer',
        'tiStatus' => 'integer',
        'tiIsDeleted' => 'integer'
    ];

    public function getAuthPassword() {
        return $this->vPassword;
    }
    
    public function adminRole(){   
        return $this->belongsTo('App\Http\Backend\Models\Role', 'iRoleId', 'iRoleId');
    }
}

app/Models/Backend/ContentPage.php
<?php

namespace App\Models\Backend;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ContentPage extends Model
{
    use HasFactory;

    protected $primaryKey = 'iPageId';
    public $timestamps = false;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'vPageUuid','vPageName','vSlug','txContent','tiIsActive','iCreatedAt','iUpdatedAt'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'iPageId'
    ];
}

app/Http/Controllers/Backend/AdminController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Common;
use App\Models\Backend\Admin;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Lang;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\MessageBag;

class AdminController extends Controller {

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct() {
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function login(Request $request) {
        if (!Auth::guard('backend')->check()) {
            $model = new Admin();
            return view('backend.admin.login',compact('model'));
        }

        return redirect()->guest(route('backend.home'));
    }

    public function dologin(Request $request) {
        // Validate form data
        $this->validate($request, [
            'vEmail' => 'required|email',
            'vPassword' => 'required',
            'iTimezoneOffset' => 'required|integer'
        ]);

        $remember_me = $request->has('remember_me') ? true : false; 
        $isLogin = Auth::guard('backend')->attempt([
            'vEmail' => $request->vEmail, 
            'password' => $request->vPassword,
            'tiIsDeleted' => 0
        ],$remember_me);
        if ($isLogin) {
            $admin = Auth::guard('backend')->user();
            if($admin->tiIsActive == 1) {
                DB::update('update admins set iLastLoginAt = ? where iAdminId = ?', [time(),$admin->iAdminId]);
                return redirect()->guest(route('backend.home'));
            } else {
                Auth::logout();
                $request->session()->flush();
                $request->session()->flash('error', 'Your account is inactive');
                return redirect()->back()->withInput($request->only('vEmail'));
            }
        }
        // Authentication failed, redirect back to the login form
        $request->session()->flash('error', 'Wrong email or password.');
        return redirect()->back()->withInput($request->only('vEmail'));
    }

    public function logout(Request $request) {
        Auth::logout();

        $request->session()->flush();
        $request->session()->regenerate();
        return redirect()->guest(route('backend.login'));
    }

    public function error() {
        return view('backend.admin.error');
    }

    //Change password
    public function ChangePassword(Request $request,MessageBag $message_bag) {
        $user = Auth::user();
        if($request->isMethod("post")) {
            // Validate form data
            $this->validate($request, [
                'vCurrentPassword' => 'required',
                'vNewPassword' => 'required|min:8|different:vCurrentPassword',
                'vConfirmPassword' => 'required_with:vNewPassword|same:vNewPassword',
            ]);

            if (!Hash::check($request->vCurrentPassword, $user->vPassword)) { 
                $message_bag->add('vCurrentPassword', __("message.old_password_wrong"));
                return Redirect::back()->withInput($request->all())->withErrors($message_bag);
            }

            $user->vPassword = Hash::make($request->vNewPassword);
            $user->save();

            FormSuccessResponse($request,"message.password_changed");
            return redirect()->route('backend.change_password');
        }
        return view('backend.admin.changepassword');
    }

    //Profile
    public function Profile(Request $request,MessageBag $message_bag) {
        $model = Auth::user();
        $validation_rules = $model->Validate("profile");
        if($request->isMethod("post")) {
            $this->ValidateForm($request,$validation_rules);
            $time = time();
            $model->vFirstName = $request->vFirstName;
            $model->vLastName = $request->vLastName;
            $model->iUpdatedAt = $time;
            $model->save();

            FormSuccessResponse($request,"message.profile_updated");
            return redirect()->route('backend.profile');
        }

        return view('backend.admin.profile',compact('model','validation_rules'));
    }
}

app/Http/Controllers/Backend/ContentPageController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Models\Backend\ContentPage;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

class ContentPageController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = ContentPage::select("vPageUuid","vPageName","vSlug","iUpdatedAt")->get();
        return view('backend.content_page.index',compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($uuid)
    {
        $model = $this->getPage($uuid);
        return view('backend.content_page.show',compact('model'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($uuid)
    {
        $model = $this->getPage($uuid);
        return view('backend.content_page.edit',compact('model'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $uuid)
    {
        $this->validate($request, [
            'vPageName' => 'required|string',
            'txContent' => 'required',
                ], [
            'vPageName.required' => 'The page name field is required.',
            'txContent.required' => 'The content field is required.',
        ]);
        try {
            $model = $this->getPage($uuid);
            $model->vPageName = $request->vPageName;
            $model->txContent = $request->txContent;
            $model->iUpdatedAt = time();
            if ($model->update()) {
                $request->session()->flash('success', $request->vPageName.' content updated successfully.');
            } else {
                $request->session()->flash('error', 'Fail to update '.$request->vTitle.' content.');
            }
            return redirect()->route('backend.content_page.show', ['content_page' => $uuid]);
        } catch (\Exception $ex) {
            $request->session()->flash('error', __('message.something_wrong'));
            return redirect()->route('backend.content_page.edit', ['content_page' => $uuid]);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    //Get page detail
    private function getPage($uuid) {
        $model = ContentPage::where(['vPageUuid' => $uuid])->first();
        if(empty($model)) {
            throw new NotFoundHttpException();
        }
        return $model;
    }
}

app/Http/Controllers/Backend/Controller.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController {
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;

    public function ValidateForm($request,$validtion_rules) {
        $rules = (isset($validtion_rules["rules"]) && !empty($validtion_rules["rules"])) ? $validtion_rules["rules"] : [];
        $message = (isset($validtion_rules["messages"]) && !empty($validtion_rules["messages"])) ? $validtion_rules["messages"] : [];
        $this->validate($request, $rules, $message);
    }
}

app/Http/Controllers/Backend/HomeController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;

class HomeController extends Controller
{
    public function index(Request $request){
        return view('backend.home.index');
    }
}

resources/views/backend/layouts/footer.blade.php
<footer class="main-footer">
    <strong>Copyright &copy; {{date('Y')}} <a href="#">{{ config('app.name') }}</a>.</strong> All rights reserved.
  </footer>

resources/views/backend/layouts/guest.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{{ (isset($title)) ? $title.' | '.config('app.name') : config('app.name') }}</title>
  <link rel="apple-touch-icon" sizes="180x180" href="{{ asset('theme/img/favicon/apple-touch-icon.png') }}">
  <link rel="icon" type="image/png" sizes="32x32" href="{{ asset('theme/img/favicon/favicon-32x32.png') }}">
  <link rel="icon" type="image/png" sizes="16x16" href="{{ asset('theme/img/favicon/favicon-16x16.png') }}">
  <link rel="manifest" href="{{ asset('theme/img/favicon/site.webmanifest') }}">
  <link rel="mask-icon" href="{{ asset('theme/img/favicon/safari-pinned-tab.svg') }}" color="#5bbad5">
  <meta name="msapplication-TileColor" content="#da532c">
  <meta name="theme-color" content="#ffffff">

  <!-- Google Font: Source Sans Pro -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ asset('theme/plugins/fontawesome-free/css/all.min.css') }}">
  <!-- icheck bootstrap -->
  <link rel="stylesheet" href="{{ asset('theme/plugins/icheck-bootstrap/icheck-bootstrap.min.css') }}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{{ asset('theme/dist/css/adminlte.min.css') }}">
</head>
<body class="hold-transition login-page">
    <div class="login-box">
        <div class="login-logo">
           <img src="{{ asset('theme/img/logo.png') }}" width="200" alt="{{ config('app.name') }}"/><br><br>
        </div>
        @yield('content')
    </div>
<!-- jQuery -->
<script src="{{ asset('theme/plugins/jquery/jquery.min.js') }}"></script>
<script>window.jQuery || document.write('<script src="{{ asset('theme/plugins/jquery/jquery.min.js') }}"><\/script>')</script>
<!-- Bootstrap 4 -->
<script src="{{ asset('theme/plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ asset('theme/dist/js/adminlte.min.js') }}"></script>
@stack('script')
</body>
</html>

resources/views/backend/layouts/header.blade.php
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
    </ul>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="fa fa-user"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                {{-- <a href="{{ route('backend.profile') }}" class="dropdown-item">
                <i class="fas fa-user"></i> Profile
                </a> --}}
                <div class="dropdown-divider"></div>
                <a href="{{ route('backend.change_password') }}" class="dropdown-item">
                <i class="fas fa-lock"></i> Change password
                </a>
                <div class="dropdown-divider"></div>
                <a href="{{ route('backend.logout') }}" class="dropdown-item">
                    <i class="fas fa-power-off"></i> Logout
                </a>
            </div>
        </li>
    </ul>
</nav>
  <!-- /.navbar -->

resources/views/backend/layouts/main.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>
            @if(View::hasSection('title'))
                @yield('title') | {{ config('app.name') }}
            @else
                {{ config('app.name') }}
            @endif
        </title>

        <link rel="apple-touch-icon" sizes="180x180" href="{{ asset('theme/img/favicon/apple-touch-icon.png') }}">
        <link rel="icon" type="image/png" sizes="32x32" href="{{ asset('theme/img/favicon/favicon-32x32.png') }}">
        <link rel="icon" type="image/png" sizes="16x16" href="{{ asset('theme/img/favicon/favicon-16x16.png') }}">
        <link rel="manifest" href="{{ asset('theme/img/favicon/site.webmanifest') }}">
        <link rel="mask-icon" href="{{ asset('theme/img/favicon/safari-pinned-tab.svg') }}" color="#5bbad5">
        <meta name="msapplication-TileColor" content="#da532c">
        <meta name="theme-color" content="#ffffff">

        @stack('top_css')
        <!-- Google Font: Source Sans Pro -->
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
        <!-- Font Awesome -->
        <link rel="stylesheet" href="{{ asset('theme/plugins/fontawesome-free/css/all.min.css') }}">
        <link rel="stylesheet" href="{{ asset('theme/plugins/jquery-toast-plugin/dist/jquery.toast.min.css') }}">
        <!-- Theme style -->
        <link rel="stylesheet" href="{{ asset('theme/dist/css/adminlte.min.css') }}">
        <link rel="stylesheet" href="{{ asset('theme/css/custom.css') }}">
        @stack('css')
    </head>
    <body class="hold-transition sidebar-mini">
        <div class="wrapper">
            @include('backend.layouts.header')
            @include('backend.layouts.sidebar')
            <div class="content-wrapper">
                <section class="content-header">
                    <div class="container-fluid">
                        <div class="row mb-2">
                            <div class="col-sm-6">
                                <h1>@yield('title')</h1>
                            </div>
                            <div class="col-sm-6">
                                <ol class="breadcrumb float-sm-right">
                                    <li class="breadcrumb-item"><a href="{{ route('backend.home') }}">Home</a></li>
                                    @yield('breadcrumb')
                                </ol>
                            </div>
                        </div>
                    </div>
                </section>
                <section class="content">
                    @yield('content')
                </section>
            </div>
            @include('backend.layouts.footer')
        </div>
        <!-- ./wrapper -->

        <!-- jQuery -->
        <script src="{{ asset('theme/plugins/jquery/jquery.min.js') }}"></script>
        <script>window.jQuery || document.write('<script src="{{ asset('theme/plugins/jquery/jquery.min.js') }}"><\/script>')</script>
        <!-- Bootstrap 4 -->
        <script src="{{ asset('theme/plugins/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
        <script src="{{ asset('theme/plugins/jquery-toast-plugin/dist/jquery.toast.min.js') }}"></script>
        <!-- AdminLTE App -->
        <script src="{{ asset('theme/dist/js/adminlte.min.js') }}"></script>
        <!-- AdminLTE for demo purposes -->
        <script src="{{ asset('theme/dist/js/demo.js') }}"></script>
        <script>
            $(function () {
                $('[data-toggle="tooltip"]').tooltip()
            });
        </script>

        @if ($message = Session::get('success'))
        <script>
            $.toast({
                heading: 'Success',
                text: '{{ $message }}',
                position: String('top-center'),
                icon: 'success',
                loaderBg: '#f96868',
                hideAfter: false,
                hideAfter: 8000
            });
        </script>
        @endif
        @if ($message = Session::get('error'))
        <script>
            $.toast({
                heading: 'Error',
                text: '{{ $message }}',
                position: 'top-center',
                icon: 'error',
                loaderBg: '#f2a654',
                hideAfter: 20000
            });
        </script>
        @endif
        @stack('script')
    </body>
</html>

resources/views/backend/layouts/sidebar.blade.php
<?php
use Illuminate\Support\Facades\Auth;
$routeArr = explode(".", app('request')->route()->getAction('as'));
?>
<!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="{{ route('backend.home') }}" class="brand-link" style="text-align:center;">
      <img src="{{ asset('theme/img/logo.png') }}" width="150" alt="{{ config('app.name') }}"/>
    </a>

    <div class="text-light" style="border-bottom:1px solid #4B545C;padding: 2px 5px 5px 5px;">
        <small><b>Last login :</b>&nbsp;&nbsp;<?= date('Y-m-d h:i A',Auth::user()->iLastLoginAt) ?></small>
    </div>

    <!-- Sidebar -->
    <div class="sidebar">
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-item">
                    <a href="{{route('backend.home')}}" class="nav-link <?= ($routeArr[1] == 'home') ? 'active' : '' ?>">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>Dashboard</p>
                    </a>
                </li>
                
                <li class="nav-item <?= ($routeArr[1] == 'content_page') ? 'menu-open' : '' ?>">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-database"></i>
                        <p>Master Data <i class="fas fa-angle-left right"></i></p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="{{ route('backend.content_page.index') }}" class="nav-link <?= ($routeArr[1] == 'content_page') ? 'active' : '' ?>">
                                <i class="fas fa-file-alt nav-icon"></i>
                                <p>Content Pages</p>
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="nav-item">
                    <a href="{{route('backend.logs')}}" class="nav-link <?= ($routeArr[1] == 'logs') ? 'active' : '' ?>">
                        <i class="nav-icon fas fa-history"></i>
                        <p>Logs</p>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
    <!-- /.sidebar -->
  </aside>